### ISSUE TITLE
stop cluster once started?

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#54]
say i deployed and something went wrong... how to remove contract then update it?

https://github.com/EvernodeXRPL/evernode-sdk/blob/main/evernode/tutorial-cluster.md

**Comment by ravinsp** [comment]
@lathanbritz :-) Once you deploy a contract, you loose control over it (the contract code is what controls it). So there are 2 ways you can do this.
1. Create a completely new cluster and deploy new/upgraded code. (this is only ok for development purposes since you will have to spend extra money for new instances and previous cluster will automatically expire after exhausting it's lease duration)
2. Include logic in your contract that you can invoke as a client so the contract will update itself. We haven't published a tutorial on this yet, so I'll explain below.

HotPocket provides a feature called "post execution script". If HotPocket finds a Linux shell script named "post_exec.sh" among your contract files after a contract invocation is complete, HotPocket will execute that script. You can use this facility to build interesting things including upgrading the contract. Here is one way you can build upgrade capability:

1. Implement a contract input message in your contract which can accept the new set code/upgrade files. It's up to you to perform any authentication/validation to avoid anyone submitting files to it.
2. Upon receiving the input, the contract can save the received files in some directory inside the contract.
3. The contract then creates "post-exec.sh" script on the contract directory (current directory) and grants it the "execute" permission (you can use nodejs fs.chmod() command). You could even receive this script as part of new upgrade files. In any case, this script should contain instructions (written in [Linux shell scripting language](https://www.shellscript.sh/)) to upgrade/replace your contract files and perform any cleanup. It's basically an "installer" script for your contract.

After the contract exits, HotPocket will simply execute the "post-exec.sh" placed by you. If the script works, next time HotPocket invokes the contract, it will be upgraded one.

We use the same mechanism in our bootstrap contract ([source code](https://github.com/EvernodeXRPL/evernode-bootstrap-contract/blob/main/src/bootstrap_contract.cpp)). When you create a new instance in Evernode, it is automatically running our bootstrap contract. It's sole purpose is to expose a contract input where you can submit your contract files (bundle.zip) and replace itself with the contents of your bundle.zip. To achieve this, the bootstrap contract is also using the above "post_exec.sh" script I explained. You can study it's source code to get an idea (but it's written in C++, you could do the same in nodejs).

**Comment by lathanbritz** [comment]
surely one should get a hashback from Evernode for the contract, then one should be allowed to redeploy with that hash and from the same account, to overwrite the deployed instance?

this would be a nice to have feature!

**Comment by ravinsp** [comment]
@lathanbritz That would break the decentralized nature. This is like a backdoor that the original developer could use to change the contract. Furthermore, any change to the contract should be done via consensus. Otherwise any changes done to individual instances will get rejected/overwritten by the majority instances.

**Comment by lathanbritz** [comment]
Surly having a easy update path for your contract, is something that should be provided? Having to write one's own implementation will be difficult for most.

Is what I'm after here.

**Comment by ravinsp** [comment]
@lathanbritz Fully agree with this. Our current expectation is these kinds of "doable-but-complicated" things will be standardized and incorporated into libraries that can be integrated into your contract as you wish. Contract upgrades is one such feature. Another one is making it easy to submit XRPL transactions without having to implement your own NPL agreement mechanisms (I remember you had to figure it out yourself and somehow achieved it). We expect these and more to be provided via libraries/tooling (by us or by community) built on top of the infrastructure provided by HotPocket. We just haven't got around to adding these features into our own libraries/tooling so for now you're on your own. :-)
