### ISSUE TITLE
contracts and hosts killing nodes

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#55]
I thought of something to night and I have not seen this covered any where. If i write a contract and deploy it, the dev has very little control over what one has deployed of that contract and that is by design from the interaction I have had via issue queues.

My question is around, if I write a contract eg. my multisig price oracle. Nothing in the boiler plate / example code covers, what happens when many nodes have either cancelled or somehow the instance has failed. 

eg. I deploy contract to 10 nodes. 2 fail, 4 are rejected as "spam" or what ever and stop the node running the contract. My contract will fail... and now updating replacing this code is non trvial in the current setup see comments https://github.com/EvernodeXRPL/evernode-sdk/issues/54#issuecomment-1354160152.

There is no way to respool another instance auto magically. To keep you contract running.

If I was after a contract thats "always up". If some random host has rejected my contract or shut down. I would like some algorithmic / automatic way of replacing that instance.

**Comment by ravinsp** [comment]
@lathanbritz good point. There are 2 scenarios we have thought about.

1. **Replenishing dead instances** - The contract can track whether other instances are still "alive" using the [contract execution context](https://github.com/EvernodeXRPL/evernode-sdk/blob/main/hotpocket/reference-contract-protocol.md#contract-execution-context) that HotPocket passes to it. Specifically the "unl" collection includes information about when the other instances was "last seen on". If the contract thinks a certain UNL node is dead, it could then purchase a new instance on some host (using the [evernode lib](https://www.npmjs.com/package/evernode-js-client)) and get the new instance joined to the cluster. This is already possible, but we haven't published documentation on this yet.

2. **The cluster going dead** - This can happen if lot of instances die/loses network at the same time, so due to lack of 80% consensus, other remaining instances will not invoke the contract as well. Unless some nodes comes back to life, this will be a deadlock and the remaining instances will slowly die out when their lease expires. Currently, there's nothing you can do about this in code. But you could setup a backup node in some host under your control, that maintains a copy of your contract and data and that node can be the seed node of spinning up a new cluster.

**Comment by lathanbritz** [comment]
1. **Sensible default** sounds good look forward to see the boiler plate code for this. Possibly that could become a default, in all contracts. Then just allow the dev's to override, making it a sensible default. As liveliness of ones cluster is really a core requirement for any contract.

2. **Multiple instances** this has a very possible risk then of having multiple instances of the contract then exiting if the previous instance comes back after the new one has been spun up. Would need some way to guarantee only one instance of the contract can run across the network. 

Rocking glad to see its been thought about.
