### ISSUE TITLE
Long running process?

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#62]
Is there a way to run a process for a long time?

app.isLoaded() in my example is always FALSE every time a new consens round comes.. how to do this?

<img width="373" alt="Screen Shot 2023-04-26 at 21 12 56" src="https://user-images.githubusercontent.com/508629/234734723-b6d50c5f-ffbc-4745-8c28-0f48b37032c9.png">

**Comment by lathanbritz** [comment]
Basically in my app here i load a Graphing tool eg. https://twitter.com/ShortTheFOMO/status/1649583563770064897?s=20 that process needs to stay open and run. It then will spit out when a tx needs to get signed at which I was then hoping to use evernode to do a multisig tx submission, back to the XRPL. Evernodes job here basically is just to get consensy to sign in my example.

But having app reinitialize every time consensys comes around is a bit of an issue here for me.

**Comment by ravinsp** [comment]
@lathanbritz This is not something HotPocket can do (at least currently). You need to reinitialize everything into memory since every contract execution is a fresh run. What you can do to help the situation is cache the last loaded graph data onto disk before the contract exits, and then populate your in-memory Graph data structures from the cache next time your contract executes.

**Comment by lathanbritz** [comment]
Thanks @ravinsp def a +1 for the future, closing this as this is by design.
