### ISSUE TITLE
hpdevkit / containers getting stuck.

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-sdk#63]
<img width="682" alt="Screen Shot 2023-04-28 at 09 55 41" src="https://user-images.githubusercontent.com/508629/235167396-bd5cbf00-8b52-4c0f-91dd-524754a95693.png">

Everything was running fine last day or two then all of a sudden the containers started failing execution. ive run hpdevkit clean, updated hpdevkit, ive run a empty contract, ive deleted the containers in docker manually, ive given docker x3 the system resources it had before.... nothing seems to get it out of this.

How / where can i get more debug to figure out what is causing the execution to fail?

**Comment by ravinsp** [comment]
@lathanbritz `Contract process execve() failed.` usually means you have something wrong specified in the bin_path or bin_args configurations. This means Hot Pocket is failing to execute your smart contract using the instructions you've specified in bin_path and bin_args. Can you post your `hp.cfg.override` file here?

**Comment by lathanbritz** [comment]
`
{
   "contract": {
      "consensus": {
            "roundtime": 6000
      }
   },
   "mesh": {
      "peer_discovery": {
            "enabled": true,
            "interval": 10000
      }
   }
}

`

**Comment by ravinsp** [comment]
Well, your config doesn't have those 2 fields as the tutorial specifies. Please include those as mentioned in the tutorial (I'm assuming yours is a nodejs contract)

**Comment by lathanbritz** [comment]
yup im nodejs

the patn one needs to spec `export EV_INSTANCE_CONFIG_PATH=<Path to your instance configuration json file>` is that an absolute path or relative one?

**Comment by ravinsp** [comment]
@lathanbritz To avoid ambiguity it's best to provide absolute path. But relative path is also supported (relative to under which directory you execute the evdevkit command)

Now that I saw that you have taken the configuration from the evdevkit tutorial, please know the configuration flow is somewhat different between when you experiment using your local pc (with hpdevkit) and when you deploy dapps to evernode network (using evdevkit). If you mix-up the two you will face confusion. You need to keep the 'bin_path', 'bin_args' fields in the hp.cfg.override file in local testing. You don't need to specify it when using evdevkit, since `evdevkit bundle` command already does it for you using the parameters you specify in that command.

**Comment by lathanbritz** [comment]
<img width="915" alt="Screen Shot 2023-04-28 at 10 44 17" src="https://user-images.githubusercontent.com/508629/235179028-67db0e3c-961f-47c8-b881-c87bdb4769f6.png">


thanks @ravinsp yeah def a little confusing that, but im following. also took me a bit to figure out that i need to copy the hp.cfg.override into the dist directory.. tutorial did not point that out only place to mentioned something around the override where to put it was that export which im assuming is only used for the production push and not for local dev.

**Comment by ravinsp** [comment]
@lathanbritz Yeah in local development, hp.cfg.override needs to be in "dist" directory. If you generate the initial project with hpdevkit this is automatically done for you (see [here](https://github.com/EvernodeXRPL/evernode-sdk/blob/main/hotpocket/tutorial-basics.md#create-the-smart-contract)).

You're right that the `export EV_INSTANCE_CONFIG_PATH` is for the production push. It is using bits and pieces from local development project (build outputs and config) but the way you use it in the commands is different :-)

I realize it is bit messy and complicated since we want to keep the flexibility on anything you might want to do without making it very easy and keeping everything hidden.

**Comment by lathanbritz** [comment]
<img width="884" alt="Screen Shot 2023-04-28 at 10 56 34" src="https://user-images.githubusercontent.com/508629/235181987-54ce4eaf-097f-4818-bf3f-82637def9843.png">
Im not getting the hp.cfg.override to apply successfully 

empty contract with debug line... fails above what does that `Error: /hpdevkit_vol/node1/contract_fs/mnt/rw/state/prebuilds/darwin-x64/node.abi93.node: invalid ELF header` mean ive done wrong?
<img width="628" alt="Screen Shot 2023-04-28 at 10 57 32" src="https://user-images.githubusercontent.com/508629/235182160-97145574-82b3-478d-84f9-43f006f19399.png">

**Comment by ravinsp** [comment]
@lathanbritz Are you building on a Mac? `darwin-x64` suggests that. Looks like this is tricky problem. You are building on the Mac and the nodejs compilation seems to be bundling together the Mac-compatible dependencies of your app. But inside HotPocket, your app will be running on Linux.

This is not something that will work out of the box with the "npm run build" command generated by hpdevkit. Do you know enough about nodejs to try and build your nodejs app using a Linux flavour? (like using a Linux-based nodejs docker image to perform your nodejs build and place the build outputs on the "dist" folder)

**Comment by lathanbritz** [comment]
ive build and run contracts here before...

Spotted the issue its the `const lmdb = require('node-lmdb')` thats causing my issue here ill go through the tickets denis had on that and his code... 

thank you kindly @ravinsp glad ive got it running again
