### ISSUE TITLE
On what occasions would the smart contract id change

### ISSUE THREAD

**Issue by marklikeapenny** [EvernodeXRPL/evernode-sdk#67]
The context object that is passed to a smart contract contains the smart contract ID `ctx.contractId`. Under what circumstances could this change (complete cluster restart, update of smart contract code) ?

**Comment by ravinsp** [comment]
@marklikeapenny This never changes during the lifetime of the instance. This is specified by the developer/entity at the time of creating the instance (see [AcquireLease](https://github.com/EvernodeXRPL/evernode-sdk/blob/main/evernode/reference-api-tenant.md#acquire-lease---async-acquireleasehostaddress-requirement-options--)). If not specified Evernode will generate an id.

The contract id is not tied to anything else like contract code or a hash. The idea is for all instances and clients of the same contract to use the same id.

**Comment by marklikeapenny** [comment]
Would it be a best practice to always specify `contractId` with `AcquireLease` and upon any code updates switch to a new one?

**Comment by ravinsp** [comment]
@marklikeapenny It would be best to specify your own contract id with AcquireLease (and repeat the same contract id all the instances you are acquiring for that contract).

Whether you should switch to a new contract id upon code updates, depends on the contract. Switching to a new contract id essentially means you have to spin up an entirely new cluster for every new version of your contract.

Instead of spinning up new clusters for new versions, HotPocket does ptovide you the ability to update your data and contract code files in-place, so you can keep using the same contract id. If you're really worried about contract versioning, HotPocket does provide a contract version attribute in the contract configuration, which you can control from your contract. So if your contract supports upgrading itself, you can update the version number too during the upgrade as shown below.

```javascript
const config = await ctx.getConfig();
config.version = "2.0";
await ctx.updateConfig(config);
```

Client applications could validate the contract id and version when connecting to HotPocket, as shown in this [js client example](https://github.com/EvernodeXRPL/hp-js-client/blob/563c282d34a473d964d540fd88a1522b1d72199a/example/client.js#L28).

**Comment by marklikeapenny** [comment]
Great explanation! Thank you.

**Comment by wojake** [comment]
What happens if I use another cluster's contract ID when acquiring instances (w/ a different state & contract)?

**Comment by ravinsp** [comment]
@wojake Nothing odd happens. You can do that. Contract ID is simply a mechanism of reducing confusion or chance of accidentally connecting to the wrong contract. Nothing more. You will not have any confusion as long as your nodes connects to other correct nodes as intended. However if one of your nodes accidentally connects (due to misconfiguration) to "wrong" nodes bearing the same contract id, your node will fall out of consensus. This is because the UNL public keys your node trusts does not match with any of the nodes of the "wrong" contract.

Even within a single Host, Sashimono does not care if multiple contract instances has the same contract id. It's not relevant for Sashimono or Evernode. It's purely for reducing confusion between contract cluster nodes and its users.
